[workspace]
members = [
    "dice-rs",
    "dice-rs-cli",
    "dice-rs-controller",
    "dice-rs-ws",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
authors = ["Andreas Schaeffer <hanack@nooblounge.net>"]
repository = "https://github.com/smearor/dice-rs"
homepage = "https://github.com/smearor/dice-rs"

[workspace.dependencies]
assert_cmd = "2"
async-trait = "0.1"
bytemuck = { version = "1", features = ["derive"] }
btleplug = "0.12"
cairo-rs = "0.22"
clap = { version = "4", features = ["derive"] }
dirs = "6"
futures = "0.3"
gl_loader = "0.1"
glam = "0.33"
glib = "0.22"
glow = "0.18"
gtk4 = "0.11"
miette = { version = "7", features = ["fancy"] }
predicates = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smallvec = "1"
tabled = "0.21"
thiserror = "2"
tokio = { version = "1", features = ["sync", "rt", "rt-multi-thread", "time", "macros", "signal", "io-std", "io-util"] }
toml = "1.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
typed-builder = "0.23"
uuid = "1"
