name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  APT_PACKAGES: curl build-essential pkg-config libdbus-1-dev

permissions:
  contents: write

jobs:
  release:
    name: Publish to crates.io
    runs-on: ubuntu-24.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v7
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ env.APT_PACKAGES }}
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build (Release Mode)
        run: cargo build --release --verbose --exclude dice-rs-controller
      - name: Dry-run publish dice-rs
        run: cargo publish --dry-run --locked -p dice-rs --token ${{ secrets.CRATES_IO_TOKEN }}
      - name: Dry-run publish dice-rs-cli
        run: cargo publish --dry-run --locked -p dice-rs-cli --token ${{ secrets.CRATES_IO_TOKEN }}
      - name: Dry-run publish dice-rs-ws
        run: cargo publish --dry-run --locked -p dice-rs-ws --token ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish dice-rs
        run: cargo publish --locked -p dice-rs --token ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish dice-rs-cli
        run: cargo publish --locked -p dice-rs-cli --token ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish dice-rs-ws
        run: cargo publish --locked -p dice-rs-ws --token ${{ secrets.CRATES_IO_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
